default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nutrition_app_development

test:
  <<: *default
  database: nutrition_app_test

production:
  <<: *default
  database: nutrition_app_production
  username: nutrition_app
  password: <%= ENV["NUTRITION_APP_DATABASE_PASSWORD"] %>
